class AppStrings {
  static const String noRouteFound = 'No route found.';

  static const String appName = 'PIPS';
  static const String appLongName = 'Public Investment Program System';
  static const String appDescription = '''
    The Public Investment Program (PIP) contains the rolling list of priority programs and projects (PAPs) to be implemented by the national government (NG), government owned and controlled corporations (GOCCs), government financial institutions (GFIs), and other national government offices and instrumentalities within the medium term, which respond to the outcomes in the Philippine Development Plan (PDP) and its Results Matrices (RM). These PAPs may be financed using national government funds, including internal cash generated by GOCCs, in partnership with the private sector or through Official Development Assistance (ODA).

    The PIP (PIP) System is a cross-platform application that facilitates the data entry of PAP and submission of updates from Agency PIP Focals, validation by the NEDA Secretariat of the priority PAPs, and report generation.
  ''';
  static const String appAuthor = 'Mark Lester Bolotaolo';

  // onboarding titles
  static const String onBoardingTitle1 = 'Title 1';
  static const String onBoardingTitle2 = 'Title 2';
  static const String onBoardingTitle3 = 'Title 3';
  static const String onBoardingTitle4 = 'Title 4';

  // onboarding subtitles
  static const String onBoardingSubtitle1 = 'Subtitle 1';
  static const String onBoardingSubtitle2 = 'Subtitle 2';
  static const String onBoardingSubtitle3 = 'Subtitle 3';
  static const String onBoardingSubtitle4 = 'Subtitle 4';

  // skip
  static const String skip = 'Skip';

  static const String unknownErrorOccured = "Unknown error occurred.";
  static const String pleaseCheckInternetConnection =
      "Please check internet connection.";

  // login screen
  static const String usernameLabelText = 'Username';
  static const String passwordLabelText = 'Password';
  static const String loginButtonText = 'Login';
  static const String registerLabelText = 'Register';
  static const String retryButtonLabelText = 'Try Again';
  static const String emailLabelText = 'Email';

  // login screen error
  static const String usernameErrorText = 'Username is invalid';
  static const String passwordErrorText = 'Password is incorrect';
  static const String emailErrorText = 'Email is invalid';

  static const String forgotPasswordLabelText = 'Forgot Password?';
  static const String resetPasswordLabelText = 'Reset Password';
  static const String resendEmailLabelText =
      'Didn\'t receive email? Resend now';

  // loading
  static const String loading = 'Loading';
  static const String ok = "OK";
  static const String success = 'Success';

  // appBarTitles
  static const String homeTitle = 'Home';
  static const String projectsTitle = 'Projects';
  static const String searchTitle = 'Search';
  static const String notificationsTitle = 'Notifications';
  static const String settingsTitle = 'Settings';

  // sectionTitle
  static const String statusOfSubmission = 'Status of Submission';
}
